config/routes.rb
RailsSc::Application.routes.draw do
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"  

  resources :colleges

  resources :reviews

  resources :baomingitems

  resources :baomings

  resources :planitems

  resources :markets

  resources :klassplans

  resources :rooms

  resources :services

  resources :courses

  resources :klasses

  resources :scores

  resources :warnings

  resources :majors

  resources :schools

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :mic, :projector, :sound, :title, :laser, :network

  has_and_belongs_to_many :klasses,:uniq=>true
  has_many :klassplans

  has_and_belongs_to_many :courses,:uniq=>true
  has_many :courseplans

  has_and_belongs_to_many :services,:uniq=>true
  has_many :serviceplans

  validates :title,:presence=>true
  
  def available_for_klass(klass)
  	if klass.projector == true && self.projector == false
  		return false
  	end

  	if klass.sound == true && self.sound == false
  		return false
  	end

  	if klass.mic == true && self.mic == false
  		return false
  	end

  	return true
  end

  def available_for_klassplan(klassplan)
    return false if klassplan.start_at == nil || klassplan.end_at == nil
    klassplans.each do |_klassplan|
      return false if !(klassplan.end_at <= _klassplan.start_at || _klassplan.end_at <= klassplan.start_at)
    end
    return true
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :projector, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :projector, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sound, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :sound, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mic, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :mic, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :laser, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :laser, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :network, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :network, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rooms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:projector) %></th>
      <th><%= model_class.human_attribute_name(:sound) %></th>
      <th><%= model_class.human_attribute_name(:mic) %></th>
      <th><%= model_class.human_attribute_name(:laser) %></th>
      <th><%= model_class.human_attribute_name(:network) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.id, room_path(room) %></td>
        <td><%= room.title %></td>
        <td><%= sf room.projector %></td>
        <td><%= sf room.sound %></td>
        <td><%= sf room.mic %></td>
        <td><%= sf room.laser %></td>
        <td><%= sf room.network %></td>
        <td><%=l room.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_room_path(room), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      room_path(room),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_room_path,
            :class => 'btn btn-primary' %>

app/views/rooms/new.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <td><strong><%= model_class.human_attribute_name(:title) %>:</strong></td>
    <td><%= @room.title %></dd>
  </tr>   
  <tr>
    <td><strong><%= model_class.human_attribute_name(:projector) %>:</strong></td>
    <td><%= sf @room.projector %></dd>
  </tr>   
  <tr>
    <td><strong><%= model_class.human_attribute_name(:sound) %>:</strong></td>
    <td><%= sf @room.sound %></dd>
  </tr>   
  <tr>
    <td><strong><%= model_class.human_attribute_name(:mic) %>:</strong></td>
    <td><%= sf @room.mic %></dd>
  </tr>   
  <tr>
    <td><strong><%= model_class.human_attribute_name(:laser) %>:</strong></td>
    <td><%= sf @room.laser %></dd>
  </tr>   
  <tr>
    <td><strong><%= model_class.human_attribute_name(:network) %>:</strong></td>
    <td><%= sf @room.network %></dd>
  </tr>   
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rooms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_room_path(@room), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              room_path(@room),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>