config/routes.rb
RailsSc::Application.routes.draw do
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"  

  resources :colleges

  resources :reviews

  resources :baomingitems

  resources :baomings

  resources :planitems

  resources :markets

  resources :klassplans

  resources :rooms

  resources :services

  resources :courses

  resources :klasses

  resources :scores

  resources :warnings

  resources :majors

  resources :schools

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'
end

app/models/college.rb
class College < ActiveRecord::Base
  attr_accessible :title
  has_many :people
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colleges }
    end
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
    @college = College.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/new
  # GET /colleges/new.json
  def new
    @college = College.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/1/edit
  def edit
    @college = College.find(params[:id])
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(params[:college])

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render json: @college, status: :created, location: @college }
      else
        format.html { render action: "new" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colleges/1
  # PUT /colleges/1.json
  def update
    @college = College.find(params[:id])

    respond_to do |format|
      if @college.update_attributes(params[:college])
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college = College.find(params[:id])
    @college.destroy

    respond_to do |format|
      format.html { redirect_to colleges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_for @college, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                colleges_path, :class => 'btn' %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/colleges/index.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= link_to college.id, college_path(college) %></td>
        <td><%= college.title %></td>
        <td><%=l college.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_college_path(college), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      college_path(college),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_college_path,
            :class => 'btn btn-primary' %>

app/views/colleges/new.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/colleges/show.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <td><strong><%= model_class.human_attribute_name(:title) %>:</strong></td>
    <td><%= @college.title %></td>
  </tr>  
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              colleges_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_college_path(@college), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              college_path(@college),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>