config/routes.rb
RailsSc::Application.routes.draw do
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"  

  resources :colleges

  resources :reviews

  resources :baomingitems

  resources :baomings

  resources :planitems

  resources :markets

  resources :klassplans

  resources :rooms

  resources :services

  resources :courses

  resources :klasses

  resources :scores

  resources :warnings

  resources :majors

  resources :schools

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'
end

app/models/klassplan.rb
class Klassplan < ActiveRecord::Base
  attr_accessible :before_klass_notification_at, :klass_id, :start_at
  belongs_to :klass
  belongs_to :room

  validates :klass, :presence => true
  validates :start_at, :presence => true
  validates :room, :presence => true  

  def end_at
    if klass && start_at
      start_at+klass.duration.day
    else
      DateTime.now+10000.day
    end
  end  
end

app/controllers/klassplans_controller.rb
class KlassplansController < ApplicationController
  # GET /klassplans
  # GET /klassplans.json
  def index
    @klassplans = Klassplan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @klassplans }
    end
  end

  # GET /klassplans/1
  # GET /klassplans/1.json
  def show
    @klassplan = Klassplan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @klassplan }
    end
  end

  # GET /klassplans/new
  # GET /klassplans/new.json
  def new
    @klassplan = Klassplan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @klassplan }
    end
  end

  # GET /klassplans/1/edit
  def edit
    @klassplan = Klassplan.find(params[:id])
  end

  # POST /klassplans
  # POST /klassplans.json
  def create
    @klassplan = Klassplan.new(params[:klassplan])

    respond_to do |format|
      if @klassplan.save
        format.html { redirect_to @klassplan, notice: 'Klassplan was successfully created.' }
        format.json { render json: @klassplan, status: :created, location: @klassplan }
      else
        format.html { render action: "new" }
        format.json { render json: @klassplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /klassplans/1
  # PUT /klassplans/1.json
  def update
    @klassplan = Klassplan.find(params[:id])

    respond_to do |format|
      if @klassplan.update_attributes(params[:klassplan])
        format.html { redirect_to @klassplan, notice: 'Klassplan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @klassplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klassplans/1
  # DELETE /klassplans/1.json
  def destroy
    @klassplan = Klassplan.find(params[:id])
    @klassplan.destroy

    respond_to do |format|
      format.html { redirect_to klassplans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/klassplans_helper.rb
module KlassplansHelper
end

app/views/klassplans/_form.html.erb
<%= form_for @klassplan, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :klass_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :klass_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :start_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :before_klass_notification_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :before_klass_notification_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :room_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :room_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                klassplans_path, :class => 'btn' %>
  </div>
<% end %>

app/views/klassplans/edit.html.erb
<%- model_class = Klassplan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/klassplans/index.html.erb
<%- model_class = Klassplan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:klass_id) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:before_klass_notification_at) %></th>
      <th><%= model_class.human_attribute_name(:room_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @klassplans.each do |klassplan| %>
      <tr>
        <td><%= link_to klassplan.id, klassplan_path(klassplan) %></td>
        <td><%= klassplan.klass_id %></td>
        <td><%= klassplan.start_at %></td>
        <td><%= klassplan.before_klass_notification_at %></td>
        <td><%= klassplan.room_id %></td>
        <td><%=l klassplan.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_klassplan_path(klassplan), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      klassplan_path(klassplan),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_klassplan_path,
            :class => 'btn btn-primary' %>

app/views/klassplans/new.html.erb
<%- model_class = Klassplan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/klassplans/show.html.erb
<%- model_class = Klassplan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:klass_id) %>:</strong></dt>
  <dd><%= @klassplan.klass_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @klassplan.start_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:before_klass_notification_at) %>:</strong></dt>
  <dd><%= @klassplan.before_klass_notification_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_id) %>:</strong></dt>
  <dd><%= @klassplan.room_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              klassplans_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_klassplan_path(@klassplan), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              klassplan_path(@klassplan),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>